apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obstruccion
spec:
  selector:
    matchLabels:
      app: obstruccion
  template:
    metadata:
      labels:
        app: obstruccion
    spec:
      nodeSelector:
        kubernetes.io/hostname: deepview-rpi5
      imagePullSecrets:
      - name: tecnoexplora-dockerhub
      containers:
      - name: obstruccion
        image: tecnoexplora/rasp-obs:v0.0.1
        command: ["python3", "main.py", "cpu"]
        env:
        - name: TZ
          value: "America/Santiago"
        - name: CONFIG_PATH
          value: "/app/config/config.yaml"
        - name: CODE_PATH
          value: /home/deepview/obstruccion/code
        - name: OUTPUT_PATH
          value: /home/deepview/obstruccion/code/data
        - name: LOGGER_PATH
          value: /app/metrics.log
        - name: LD_LIBRARY_PATH
          value: /usr/lib/hailort
        - name: DB_NAME
          value: "dbname"
        - name: DB_USER
          value: "dbuser"
        - name: DB_PASSWORD
          value: "pass765ghjx"
        - name: DB_HOST
          value: "192.168.194.97"
        - name: DB_PORT
          value: "5032"
        - name: SECRET_KEY 
          value: "4Tfi3VjjpFg-P7qouw5Xf7N20QEDkjntIWBWZQvuLuY="
        - name: API_ENDPOINT
          value: "http://192.168.101.212:8081/api/alerts/set_alarm/"
        volumeMounts:
        - mountPath: /mnt
          name: nfs-volume
        - name: code
          mountPath: /app
        - name: data
          mountPath: /data
        securityContext:
          privileged: true
        stdin: true
        tty: true
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-rpi1
      - name: code
        hostPath:
          path: /home/deepview/obstruccion/code
          type: Directory
      - name: data
        hostPath:
          path: /home/deepview/obstruccion/code/data
          type: Directory
      - name: hailo-device
        hostPath:
          path: /dev/hailo0
          type: CharDevice
      volumeDevices:
      - name: hailo-device
        devicePath: /dev/hailo0
