apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-rpi1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /srv/nfs/rpi1
    server: rancher.deepview.cl