apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-rpi1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv-rpi1
  storageClassName: nfs