name: app-alerts-review
services:

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - consumer_review

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass765ghjx
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_review:/var/lib/postgresql/data/
    networks:
      - consumer_review

  web-review:
    env_file:
      - .env
    image: tecnoexplora/app-alerts-back:latest
    volumes:
      - log_data_review:/api_alerts/project_alerts/logs
      - ${IMAGE_BASE_DIR}:/app/images
      - ${SCRIPT_DIR}:/app/scripts
      - ${HOME_DIR}:/app/home
      - ${APP_BUILD_DIR}:/app/www
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    tty: true
    networks:
      - consumer_review
      - app-network

networks:
  consumer_review: 
    driver: bridge
  app-network:
    name: app-network 
    driver: bridge
    external: true

volumes:
  postgres_data_review:
  log_data_review: